server:
  port: 7003

eureka:
  instance: #eureka实例定义
    hostname: eureka3 #定义Eureka 实例所在的主机名称
  client:
    fetch-registry: false #是否要从eureka获取注册信息
    register-with-eureka: false #是否注册到eureka
    service-url:
#      defaultZone: http://admin:admin@localhost:7001/eureka
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60杪）
    enable-replicated-request-compression: false  #设置为false表示关闭保护模式
spring:
  security:
    user:
      name: admin
      password: admin