server:
  port: 80


feign:
  hystrix:
    enabled: true   #断路器需要手启动开启，默认是关闭状态

  compression:
    request:
      enabled: true
      mine-types: #可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 #超过2048的字节进行压缩


eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
    register-with-eureka: false #不需要注册到eureka中


spring:
  application:
    name: microcloud-consumer-feign


logging:
  level:
    com.infocity.service: debug


