server:
  port: 80

spring:
  application:
    name: microcloud-consumer


ribbon:
  eureka:
    enabled: false

MICROCLOUD-PROVIDER-PRODUCT:
  ribbon:
    listOfServers: http://localhost:8080,http://localhost:8081,http://localhost:8082


